# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cookingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainWindowLabel = QtWidgets.QLabel(self.centralwidget)
        self.mainWindowLabel.setGeometry(QtCore.QRect(0, 0, 800, 32))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.mainWindowLabel.setFont(font)
        self.mainWindowLabel.setAutoFillBackground(False)
        self.mainWindowLabel.setScaledContents(False)
        self.mainWindowLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mainWindowLabel.setObjectName("mainWindowLabel")
        self.mainButton = QtWidgets.QPushButton(self.centralwidget)
        self.mainButton.setEnabled(True)
        self.mainButton.setGeometry(QtCore.QRect(630, 510, 150, 25))
        self.mainButton.setFlat(False)
        self.mainButton.setObjectName("mainButton")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 90, 781, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.cookingGrid = QtWidgets.QGridLayout(self.layoutWidget)
        self.cookingGrid.setContentsMargins(0, 0, 0, 0)
        self.cookingGrid.setObjectName("cookingGrid")
        self.recipesButton = QtWidgets.QPushButton(self.layoutWidget)
        self.recipesButton.setEnabled(True)
        self.recipesButton.setFlat(False)
        self.recipesButton.setObjectName("recipesButton")
        self.cookingGrid.addWidget(self.recipesButton, 0, 0, 1, 1)
        self.xpButton = QtWidgets.QPushButton(self.layoutWidget)
        self.xpButton.setEnabled(False)
        self.xpButton.setFlat(False)
        self.xpButton.setObjectName("xpButton")
        self.cookingGrid.addWidget(self.xpButton, 0, 1, 1, 1)
        self.masteryButton = QtWidgets.QPushButton(self.layoutWidget)
        self.masteryButton.setEnabled(False)
        self.masteryButton.setFlat(False)
        self.masteryButton.setObjectName("masteryButton")
        self.cookingGrid.addWidget(self.masteryButton, 0, 2, 1, 1)
        self.toolsButton = QtWidgets.QPushButton(self.layoutWidget)
        self.toolsButton.setEnabled(False)
        self.toolsButton.setFlat(False)
        self.toolsButton.setObjectName("toolsButton")
        self.cookingGrid.addWidget(self.toolsButton, 0, 3, 1, 1)
        self.guidsButton = QtWidgets.QPushButton(self.layoutWidget)
        self.guidsButton.setEnabled(False)
        self.guidsButton.setFlat(False)
        self.guidsButton.setObjectName("guidsButton")
        self.cookingGrid.addWidget(self.guidsButton, 0, 4, 1, 1)
        self.cookingList = QtWidgets.QListWidget(self.centralwidget)
        self.cookingList.setGeometry(QtCore.QRect(10, 130, 310, 350))
        self.cookingList.setObjectName("cookingList")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(335, 130, 455, 350))
        self.textBrowser.setObjectName("textBrowser")
        self.calculateButton = QtWidgets.QPushButton(self.centralwidget)
        self.calculateButton.setEnabled(False)
        self.calculateButton.setGeometry(QtCore.QRect(470, 510, 150, 25))
        self.calculateButton.setFlat(False)
        self.calculateButton.setObjectName("calculateButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mainWindowLabel.setText(_translate("MainWindow", "Cooking"))
        self.mainButton.setText(_translate("MainWindow", "Main"))
        self.recipesButton.setText(_translate("MainWindow", "Recipes"))
        self.xpButton.setText(_translate("MainWindow", "Cooking XP"))
        self.masteryButton.setText(_translate("MainWindow", "Cooking Mastery"))
        self.toolsButton.setText(_translate("MainWindow", "Cooking Tools"))
        self.guidsButton.setText(_translate("MainWindow", "Guids"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Effect:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Heatstroke, Hypothermia Resistance +10%, Auto-Fishing time -5%, Movement Speed +2, Critical Hit +1</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ingredience:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">10</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">EX:</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.calculateButton.setText(_translate("MainWindow", "Calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
